// Import Material Design 3 Web Components
import '@material/web/button/filled-button.js';
import '@material/web/button/outlined-button.js';
import '@material/web/textfield/outlined-text-field.js';
import '@material/web/progress/circular-progress.js';
import '@material/web/slider/slider.js';
import '@material/web/icon/icon.js';

// Import WASM module generated by wasm-pack
import init, { QuantumWormholeEngine } from '../crate/pkg/quantum_wormhole.js';

// Elements
const canvas = document.getElementById('wormhole-canvas') as HTMLCanvasElement;
const ctx = canvas.getContext('2d', { alpha: false })!;

const inputName = document.getElementById('input-name') as any;
const inputDob = document.getElementById('input-dob') as any;

const btnGenerate = document.getElementById('btn-generate') as HTMLElement;
const btnSave = document.getElementById('btn-save') as HTMLElement;
const btnToggleAnim = document.getElementById('btn-toggle-anim') as HTMLElement;
const animIcon = document.getElementById('anim-icon') as HTMLElement;
const animText = document.getElementById('anim-text') as HTMLElement;

const sliderWarp = document.getElementById('slider-warp') as any;
const sliderFlux = document.getElementById('slider-flux') as any;
const sliderSpeed = document.getElementById('slider-speed') as any;

const valWarp = document.getElementById('val-warp') as HTMLElement;
const valFlux = document.getElementById('val-flux') as HTMLElement;
const valSpeed = document.getElementById('val-speed') as HTMLElement;

const hudFps = document.getElementById('hud-fps') as HTMLElement;
const hudHash = document.getElementById('hud-hash') as HTMLElement;
const loader = document.getElementById('canvas-loader') as HTMLElement;

const teleHorizon = document.getElementById('tele-horizon') as HTMLElement;
const teleEnergy = document.getElementById('tele-energy') as HTMLElement;
const teleDoppler = document.getElementById('tele-doppler') as HTMLElement;

// App State
let engine: QuantumWormholeEngine | null = null;
let isAnimating = true;
let animationFrameId: number | null = null;
let lastFrameTime = performance.now();
let frameCount = 0;
let fpsTimer = performance.now();
let timeOffset = 0;

// Simple string hasher for seed display & telemetry telemetry calculation
async function computeHash(str: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(str);
  const hashBuffer = await crypto.subtle.digest('SHA-256', data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

// Update telemetry info based on hash
async function updateTelemetry(name: string, dob: string) {
  const hashStr = await computeHash(`${name}:${dob}`);
  const shortHash = `0x${hashStr.substring(0, 8).toUpperCase()}`;
  hudHash.textContent = shortHash;

  // Derive pseudo metrics for high-tech HUD feel
  const h1 = parseInt(hashStr.substring(0, 4), 16);
  const h2 = parseInt(hashStr.substring(4, 8), 16);
  const h3 = parseInt(hashStr.substring(8, 12), 16);

  const horizonKm = (12.4 + (h1 % 850) / 10).toFixed(2);
  const energyPev = ((h2 % 9000) / 100 + 10.5).toFixed(1);
  const dopplerZ = ((h3 % 1000) / 2000 + 0.15).toFixed(3);

  teleHorizon.textContent = `${horizonKm} km`;
  teleEnergy.textContent = `${energyPev} PeV`;
  teleDoppler.textContent = `z = +${dopplerZ}`;
}

// Main Render Loop
function renderFrame(now: number) {
  if (!engine) return;

  const delta = (now - lastFrameTime) / 1000;
  lastFrameTime = now;

  // FPS calculation
  frameCount++;
  if (now - fpsTimer >= 500) {
    const currentFps = Math.round((frameCount * 1000) / (now - fpsTimer));
    hudFps.textContent = currentFps.toString();
    frameCount = 0;
    fpsTimer = now;
  }

  const speedMultiplier = parseFloat(sliderSpeed.value ?? '1.0');
  if (isAnimating) {
    timeOffset += delta * speedMultiplier;
  }

  const name = inputName.value || 'Mozi Quantum';
  const dob = inputDob.value || '2000-01-01';
  const warp = parseFloat(sliderWarp.value ?? '1.0');
  const flux = parseFloat(sliderFlux.value ?? '1.0');

  // Call Rust WASM Engine to compute RGBA pixel buffer
  const pixelArray = engine.render(name, dob, timeOffset, warp, flux);
  
  // Wrap into ImageData and paint onto canvas
  const imgData = new ImageData(
    new Uint8ClampedArray(pixelArray.buffer as ArrayBuffer, pixelArray.byteOffset, pixelArray.byteLength),
    512,
    512
  );
  ctx.putImageData(imgData, 0, 0);

  if (isAnimating) {
    animationFrameId = requestAnimationFrame(renderFrame);
  }
}

// Start or Resume Animation
function startAnimation() {
  if (!isAnimating) {
    isAnimating = true;
    animIcon.textContent = 'pause';
    animText.textContent = '暂停动态 (Pause)';
    lastFrameTime = performance.now();
    animationFrameId = requestAnimationFrame(renderFrame);
  }
}

// Pause Animation
function pauseAnimation() {
  isAnimating = false;
  animIcon.textContent = 'play_arrow';
  animText.textContent = '播放动态 (Play)';
  if (animationFrameId !== null) {
    cancelAnimationFrame(animationFrameId);
    animationFrameId = null;
  }
}

// Trigger Manual Render
function triggerRender() {
  const name = inputName.value || 'Mozi Quantum';
  const dob = inputDob.value || '2000-01-01';
  updateTelemetry(name, dob);

  if (!isAnimating) {
    renderFrame(performance.now());
  }
}

// Initialize Application
async function initApp() {
  try {
    loader.classList.remove('hidden');
    // Load WASM package
    await init();
    engine = new QuantumWormholeEngine(512, 512);

    loader.classList.add('hidden');

    // Initial Telemetry & Animation Start
    const initialName = inputName.value || 'Mozi Quantum';
    const initialDob = inputDob.value || '2000-01-01';
    updateTelemetry(initialName, initialDob);

    lastFrameTime = performance.now();
    animationFrameId = requestAnimationFrame(renderFrame);

    // Setup Event Handlers
    btnGenerate.addEventListener('click', () => {
      timeOffset = 0; // Reset warp swirl
      triggerRender();
      if (!isAnimating) startAnimation();
    });

    btnToggleAnim.addEventListener('click', () => {
      if (isAnimating) {
        pauseAnimation();
      } else {
        startAnimation();
      }
    });

    btnSave.addEventListener('click', () => {
      const link = document.createElement('a');
      const name = (inputName.value || 'quantum').replace(/\s+/g, '_');
      link.download = `wormhole_${name}_512x512.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    });

    // Inputs listeners
    inputName.addEventListener('input', () => triggerRender());
    inputDob.addEventListener('input', () => triggerRender());

    // Sliders listeners
    sliderWarp.addEventListener('input', () => {
      valWarp.textContent = parseFloat(sliderWarp.value).toFixed(1);
      triggerRender();
    });

    sliderFlux.addEventListener('input', () => {
      valFlux.textContent = parseFloat(sliderFlux.value).toFixed(1);
      triggerRender();
    });

    sliderSpeed.addEventListener('input', () => {
      valSpeed.textContent = parseFloat(sliderSpeed.value).toFixed(1);
    });

  } catch (err) {
    console.error('Failed to initialize Rust WASM Quantum Engine:', err);
    loader.querySelector('.loader-text')!.textContent = 'WASM 初始化失败';
  }
}

// Run app init
initApp();
