// Import Material Design 3 Web Components
import '@material/web/button/filled-button.js';
import '@material/web/button/filled-tonal-button.js';
import '@material/web/button/outlined-button.js';
import '@material/web/textfield/outlined-text-field.js';
import '@material/web/progress/circular-progress.js';
import '@material/web/slider/slider.js';
import '@material/web/icon/icon.js';
import '@material/web/iconbutton/icon-button.js';
import '@material/web/select/outlined-select.js';
import '@material/web/select/select-option.js';

// Import WASM module generated by wasm-pack
import init, { QuantumWormholeEngine } from '../crate/pkg/quantum_wormhole.js';

// 模块化功能：i18n / 彩蛋 / 音效 / Toast
import {
  getLocale,
  setLocale,
  t,
  applyTranslations,
  formatMonthYear,
  formatHeadlineDate,
  weekdayShortNames,
  formatYear,
  LOCALE_NAMES,
  type AppLocale,
} from './i18n';
import { findEasterEgg, type EasterEgg } from './easter-eggs';
import { AudioManager } from './audio';
import { showToast } from './toast';

// 应用版本号（沿用旧版语义）
export const VERSION = 'v1.2.0';

// DOM Elements
const canvas = document.getElementById('wormhole-canvas') as HTMLCanvasElement;
const ctx = canvas.getContext('2d', { alpha: false })!;
const canvasFrame = document.getElementById('canvas-frame') as HTMLElement;

const inputName = document.getElementById('input-name') as any;
const inputDob = document.getElementById('input-dob') as any;
const btnOpenDatepicker = document.getElementById('btn-open-datepicker') as HTMLElement;

const standbyOverlay = document.getElementById('standby-overlay') as HTMLElement;

const btnToggleEngine = document.getElementById('btn-toggle-engine') as any;
const engineBtnIcon = document.getElementById('engine-btn-icon') as HTMLElement;
const engineBtnText = document.getElementById('engine-btn-text') as HTMLElement;

const btnSave = document.getElementById('btn-save') as HTMLElement;

const sliderWarp = document.getElementById('slider-warp') as any;
const sliderFlux = document.getElementById('slider-flux') as any;
const sliderSpeed = document.getElementById('slider-speed') as any;

const valWarp = document.getElementById('val-warp') as HTMLElement;
const valFlux = document.getElementById('val-flux') as HTMLElement;
const valSpeed = document.getElementById('val-speed') as HTMLElement;

const hudFps = document.getElementById('hud-fps') as HTMLElement;
const hudHash = document.getElementById('hud-hash') as HTMLElement;
const hudStatus = document.getElementById('hud-status') as HTMLElement;
const statusDot = document.getElementById('status-dot') as HTMLElement;
const loader = document.getElementById('canvas-loader') as HTMLElement;

const teleHorizon = document.getElementById('tele-horizon') as HTMLElement;
const teleEnergy = document.getElementById('tele-energy') as HTMLElement;
const teleDoppler = document.getElementById('tele-doppler') as HTMLElement;

// i18n / 彩蛋 / 音效元素
const langSelect = document.getElementById('lang-select') as any;
const btnSound = document.getElementById('btn-sound') as HTMLElement;
const soundIcon = document.getElementById('sound-icon') as HTMLElement;
const eggBadge = document.getElementById('egg-badge') as HTMLElement;
const eggBadgeText = document.getElementById('egg-badge-text') as HTMLElement;
const appVersion = document.getElementById('app-version') as HTMLElement;

// M3 Date Picker Elements
const m3DateDialog = document.getElementById('m3-date-dialog') as HTMLDialogElement;
const m3DatePickerSelected = document.getElementById('m3-date-picker-selected') as HTMLElement;
const btnDateModeToggle = document.getElementById('btn-date-mode-toggle') as HTMLElement;
const modeToggleIcon = document.getElementById('mode-toggle-icon') as HTMLElement;

const m3CalendarView = document.getElementById('m3-calendar-view') as HTMLElement;
const m3YearView = document.getElementById('m3-year-view') as HTMLElement;
const m3InputView = document.getElementById('m3-input-view') as HTMLElement;

const m3MonthYearBtn = document.getElementById('m3-month-year-btn') as HTMLElement;
const m3MonthYearTitle = document.getElementById('m3-month-year-title') as HTMLElement;
const m3WeekdayHeader = document.getElementById('m3-weekday-header') as HTMLElement;
const m3DaysContainer = document.getElementById('m3-days-container') as HTMLElement;
const m3YearsContainer = document.getElementById('m3-years-container') as HTMLElement;
const m3TextFieldDate = document.getElementById('m3-text-field-date') as any;

const btnPrevMonth = document.getElementById('btn-prev-month') as HTMLElement;
const btnNextMonth = document.getElementById('btn-next-month') as HTMLElement;
const btnDateCancel = document.getElementById('btn-date-cancel') as HTMLElement;
const btnDateConfirm = document.getElementById('btn-date-confirm') as HTMLElement;

// App Engine State
type EngineState = 'STOPPED' | 'RUNNING';
type DatePickerViewMode = 'CALENDAR' | 'YEAR_SELECT' | 'TEXT_INPUT';

let engine: QuantumWormholeEngine | null = null;
let engineState: EngineState = 'STOPPED';
let animationFrameId: number | null = null;
let lastFrameTime = performance.now();
let frameCount = 0;
let fpsTimer = performance.now();
let timeOffset = 0;
let wasRunningBeforeHide = false;

// 彩蛋 / 音效
let activeEgg: EasterEgg | null = null;
const audio = new AudioManager('audio/');
const SOUND_STORAGE_KEY = 'qw.sound';

// M3 DatePicker State
let currentSelectedDate = new Date(2000, 0, 1);
let activePickerYear = 2000;
let activePickerMonth = 0;
let tempSelectedDate = new Date(2000, 0, 1);
let datePickerMode: DatePickerViewMode = 'CALENDAR';

/* ------------------------------------------------------------------ */
/* 工具函数                                                            */
/* ------------------------------------------------------------------ */

// Compute SHA-256 Hash for input seed display
async function computeHash(str: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(str);
  const hashBuffer = await crypto.subtle.digest('SHA-256', data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

// 32bit 哈希（旧版 getHash，用于音效种子）
function getSeed(name: string, dob: string): number {
  const input = `${name}${dob}`;
  let hash = 0;
  for (let i = 0; i < input.length; i++) {
    const chr = input.charCodeAt(i);
    hash = (hash << 5) - hash + chr;
    hash |= 0;
  }
  return hash;
}

/* ------------------------------------------------------------------ */
/* 音效                                                                */
/* ------------------------------------------------------------------ */

function initSoundToggle() {
  const saved = localStorage.getItem(SOUND_STORAGE_KEY);
  const enabled = saved === null ? true : saved === '1';
  audio.setEnabled(enabled);
  syncSoundIcon();
  btnSound.addEventListener('click', () => {
    audio.setEnabled(!audio.enabled);
    localStorage.setItem(SOUND_STORAGE_KEY, audio.enabled ? '1' : '0');
    syncSoundIcon();
    showToast(audio.enabled ? t('app.soundOn') : t('app.soundOff'));
  });
}

function syncSoundIcon() {
  soundIcon.textContent = audio.enabled ? 'volume_up' : 'volume_off';
  btnSound.title = audio.enabled ? t('app.soundOff') : t('app.soundOn');
}

/* ------------------------------------------------------------------ */
/* 彩蛋                                                                */
/* ------------------------------------------------------------------ */

/** 根据当前姓名输入刷新彩蛋状态（角标显隐 + 文案）。 */
function updateEggState(): void {
  const name = inputName.value || '';
  activeEgg = findEasterEgg(name);

  if (activeEgg) {
    eggBadgeText.textContent = `🥚 ${t(`egg.${activeEgg.id}`)}`;
    eggBadge.title = t('egg.badgeHint');
    eggBadge.classList.remove('hidden');
  } else {
    eggBadge.classList.add('hidden');
  }
}

/* ------------------------------------------------------------------ */
/* 遥测 / HUD                                                          */
/* ------------------------------------------------------------------ */

// Update telemetry display metrics
async function updateTelemetry(name: string, dob: string) {
  const hashStr = await computeHash(`${name}:${dob}`);
  const shortHash = `0x${hashStr.substring(0, 8).toUpperCase()}`;
  hudHash.textContent = shortHash;

  const h1 = parseInt(hashStr.substring(0, 4), 16);
  const h2 = parseInt(hashStr.substring(4, 8), 16);
  const h3 = parseInt(hashStr.substring(8, 12), 16);

  const horizonKm = (12.4 + (h1 % 850) / 10).toFixed(2);
  const energyPev = ((h2 % 9000) / 100 + 10.5).toFixed(1);
  const dopplerZ = ((h3 % 1000) / 2000 + 0.15).toFixed(3);

  teleHorizon.textContent = `${horizonKm} km`;
  teleEnergy.textContent = `${energyPev} PeV`;
  teleDoppler.textContent = `z = +${dopplerZ}`;
}

// Render a single frame from WASM engine
function renderSingleFrame() {
  if (!engine) return;

  const name = inputName.value || 'Mozi Quantum';
  const dob = inputDob.value || '2000-01-01';
  const warp = parseFloat(sliderWarp.value ?? '1.0');
  const flux = parseFloat(sliderFlux.value ?? '1.0');

  const pixelArray = engine.render(name, dob, timeOffset, warp, flux);

  const imgData = new ImageData(
    new Uint8ClampedArray(pixelArray.buffer as ArrayBuffer, pixelArray.byteOffset, pixelArray.byteLength),
    512,
    512
  );
  ctx.putImageData(imgData, 0, 0);

  updateTelemetry(name, dob);
}

// Main Animation Loop
function renderLoop(now: number) {
  if (engineState !== 'RUNNING' || !engine) return;

  const delta = (now - lastFrameTime) / 1000;
  lastFrameTime = now;

  frameCount++;
  if (now - fpsTimer >= 500) {
    const currentFps = Math.round((frameCount * 1000) / (now - fpsTimer));
    hudFps.textContent = currentFps.toString();
    frameCount = 0;
    fpsTimer = now;
  }

  const speedMultiplier = parseFloat(sliderSpeed.value ?? '1.0');
  timeOffset += delta * speedMultiplier;

  renderSingleFrame();

  animationFrameId = requestAnimationFrame(renderLoop);
}

// Start Engine Execution
function startEngine() {
  if (!engine) return;

  engineState = 'RUNNING';
  standbyOverlay.classList.add('hidden');

  engineBtnIcon.textContent = 'stop';
  engineBtnText.textContent = t('engine.stop');

  hudStatus.textContent = t('hud.status.running');
  statusDot.className = 'status-dot active';

  lastFrameTime = performance.now();
  fpsTimer = performance.now();
  frameCount = 0;

  if (animationFrameId !== null) cancelAnimationFrame(animationFrameId);
  animationFrameId = requestAnimationFrame(renderLoop);
}

// Stop Engine Execution completely (0% CPU)
function stopEngine() {
  engineState = 'STOPPED';
  if (animationFrameId !== null) {
    cancelAnimationFrame(animationFrameId);
    animationFrameId = null;
  }

  standbyOverlay.classList.remove('hidden');

  engineBtnIcon.textContent = 'play_arrow';
  engineBtnText.textContent = t('engine.start');

  hudStatus.textContent = t('hud.status.standby');
  statusDot.className = 'status-dot';
  hudFps.textContent = '0';
}

/* ------------------------------------------------------------------ */
/* 日期选择器                                                          */
/* ------------------------------------------------------------------ */

// Format date to YYYY-MM-DD
function formatDate(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

// Update Top Headline Text
function updatePickerHeadline() {
  m3DatePickerSelected.textContent = formatHeadlineDate(tempSelectedDate);
}

// 渲染周表头（跟随语言环境）
function renderWeekdayHeader() {
  m3WeekdayHeader.innerHTML = '';
  for (const name of weekdayShortNames()) {
    const span = document.createElement('span');
    span.textContent = name;
    m3WeekdayHeader.appendChild(span);
  }
}

// Switch between Date Picker View Modes
function switchPickerView(mode: DatePickerViewMode) {
  datePickerMode = mode;

  m3CalendarView.classList.add('hidden');
  m3YearView.classList.add('hidden');
  m3InputView.classList.add('hidden');

  m3MonthYearBtn.classList.remove('active');

  if (mode === 'CALENDAR') {
    m3CalendarView.classList.remove('hidden');
    modeToggleIcon.textContent = 'edit';
    btnDateModeToggle.title = t('datepicker.toggleText');
    renderM3Calendar();
  } else if (mode === 'YEAR_SELECT') {
    m3YearView.classList.remove('hidden');
    m3MonthYearBtn.classList.add('active');
    modeToggleIcon.textContent = 'edit';
    renderM3YearView();
  } else if (mode === 'TEXT_INPUT') {
    m3InputView.classList.remove('hidden');
    modeToggleIcon.textContent = 'calendar_month';
    btnDateModeToggle.title = t('datepicker.toggleCalendar');
    m3TextFieldDate.value = formatDate(tempSelectedDate);
  }

  updatePickerHeadline();
}

// Render Calendar Days Grid for M3 DatePicker
function renderM3Calendar() {
  m3MonthYearTitle.textContent = formatMonthYear(activePickerYear, activePickerMonth);
  updatePickerHeadline();

  m3DaysContainer.innerHTML = '';

  const firstDayOfWeek = new Date(activePickerYear, activePickerMonth, 1).getDay();
  const totalDays = new Date(activePickerYear, activePickerMonth + 1, 0).getDate();

  const today = new Date();
  const isTodayMonth = today.getFullYear() === activePickerYear && today.getMonth() === activePickerMonth;
  const todayDate = today.getDate();

  // Empty cells before first day
  for (let i = 0; i < firstDayOfWeek; i++) {
    const emptyCell = document.createElement('div');
    emptyCell.className = 'm3-day-cell empty';
    m3DaysContainer.appendChild(emptyCell);
  }

  // Days cells
  for (let day = 1; day <= totalDays; day++) {
    const cell = document.createElement('div');
    cell.className = 'm3-day-cell';
    cell.textContent = day.toString();

    // Check if cell is today
    if (isTodayMonth && day === todayDate) {
      cell.classList.add('today');
    }

    // Check if cell is selected
    const cellDate = new Date(activePickerYear, activePickerMonth, day);
    if (
      cellDate.getFullYear() === tempSelectedDate.getFullYear() &&
      cellDate.getMonth() === tempSelectedDate.getMonth() &&
      cellDate.getDate() === tempSelectedDate.getDate()
    ) {
      cell.classList.add('selected');
    }

    cell.addEventListener('click', () => {
      tempSelectedDate = new Date(activePickerYear, activePickerMonth, day);
      renderM3Calendar();
    });

    m3DaysContainer.appendChild(cell);
  }
}

// Render Year Selection Grid
function renderM3YearView() {
  m3YearsContainer.innerHTML = '';
  const currentYear = activePickerYear;

  let selectedEl: HTMLElement | null = null;

  for (let year = 1920; year <= 2035; year++) {
    const yearCell = document.createElement('div');
    yearCell.className = 'm3-year-cell';
    yearCell.textContent = formatYear(year);

    if (year === currentYear) {
      yearCell.classList.add('selected');
      selectedEl = yearCell;
    }

    yearCell.addEventListener('click', () => {
      activePickerYear = year;
      tempSelectedDate.setFullYear(year);
      switchPickerView('CALENDAR');
    });

    m3YearsContainer.appendChild(yearCell);
  }

  if (selectedEl) {
    setTimeout(() => {
      selectedEl?.scrollIntoView({ block: 'center', behavior: 'smooth' });
    }, 50);
  }
}

// Open M3 Date Picker Dialog
function openDatePicker() {
  const parts = (inputDob.value || '2000-01-01').split('-').map(Number);
  if (parts.length === 3 && !isNaN(parts[0]) && !isNaN(parts[1]) && !isNaN(parts[2])) {
    currentSelectedDate = new Date(parts[0], parts[1] - 1, parts[2]);
  } else {
    currentSelectedDate = new Date(2000, 0, 1);
  }

  tempSelectedDate = new Date(currentSelectedDate);
  activePickerYear = tempSelectedDate.getFullYear();
  activePickerMonth = tempSelectedDate.getMonth();

  switchPickerView('CALENDAR');
  m3DateDialog.showModal();
}

/* ------------------------------------------------------------------ */
/* 语言切换                                                            */
/* ------------------------------------------------------------------ */

/** 语言切换后刷新所有动态文案。 */
function refreshDynamicText() {
  engineBtnText.textContent =
    engineState === 'RUNNING' ? t('engine.stop') : t('engine.start');
  hudStatus.textContent =
    engineState === 'RUNNING' ? t('hud.status.running') : t('hud.status.standby');
  syncSoundIcon();
  updateEggState();

  if (datePickerMode === 'CALENDAR') {
    btnDateModeToggle.title = t('datepicker.toggleText');
    renderM3Calendar();
  } else if (datePickerMode === 'TEXT_INPUT') {
    btnDateModeToggle.title = t('datepicker.toggleCalendar');
  }
  updatePickerHeadline();
}

/* ------------------------------------------------------------------ */
/* 初始化                                                              */
/* ------------------------------------------------------------------ */

// Initialize WASM and Application Event Listeners
async function initApp() {
  try {
    // 初始语言环境（浏览器检测 → localStorage 持久化）
    applyTranslations();
    langSelect.value = getLocale();
    appVersion.textContent = VERSION;
    renderWeekdayHeader();
    initSoundToggle();
    refreshDynamicText();

    loader.classList.remove('hidden');
    await init();
    engine = new QuantumWormholeEngine(512, 512);

    loader.classList.add('hidden');

    const initialName = inputName.value || 'Mozi Quantum';
    const initialDob = inputDob.value || '2000-01-01';
    updateTelemetry(initialName, initialDob);

    renderSingleFrame();

    // 画布点击：彩蛋 → 音效/跳转；停止态 → 启动引擎；运行态 → 音效
    canvasFrame.addEventListener('click', () => {
      const seed = getSeed(inputName.value || 'Mozi Quantum', inputDob.value || '2000-01-01');

      if (activeEgg) {
        audio.playRandom(seed);
        showToast(`${t('egg.toast')}：${t(`egg.${activeEgg.id}`)}`);
        window.open(activeEgg.redirectURL, '_blank', 'noopener');
      } else if (engineState === 'STOPPED') {
        audio.playRandom(seed);
        startEngine();
      } else {
        audio.playRandom(seed);
      }
    });

    btnToggleEngine.addEventListener('click', () => {
      if (engineState === 'STOPPED') {
        startEngine();
      } else {
        stopEngine();
      }
    });

    btnSave.addEventListener('click', () => {
      const link = document.createElement('a');
      const name = (inputName.value || 'quantum').replace(/\s+/g, '_');
      link.download = `wormhole_${name}_512x512.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    });

    // 语言切换
    langSelect.addEventListener('change', () => {
      const locale = langSelect.value as AppLocale;
      setLocale(locale);
      applyTranslations();
      renderWeekdayHeader();
      refreshDynamicText();
      showToast(LOCALE_NAMES[locale]);
    });

    // M3 Date Picker Event Handlers
    inputDob.addEventListener('click', openDatePicker);
    btnOpenDatepicker.addEventListener('click', (e: Event) => {
      e.stopPropagation();
      openDatePicker();
    });

    // Header Pencil / Mode Toggle
    btnDateModeToggle.addEventListener('click', () => {
      if (datePickerMode === 'TEXT_INPUT') {
        switchPickerView('CALENDAR');
      } else {
        switchPickerView('TEXT_INPUT');
      }
    });

    // Month-Year Dropdown Button
    m3MonthYearBtn.addEventListener('click', () => {
      if (datePickerMode === 'YEAR_SELECT') {
        switchPickerView('CALENDAR');
      } else {
        switchPickerView('YEAR_SELECT');
      }
    });

    btnPrevMonth.addEventListener('click', () => {
      activePickerMonth--;
      if (activePickerMonth < 0) {
        activePickerMonth = 11;
        activePickerYear--;
      }
      renderM3Calendar();
    });

    btnNextMonth.addEventListener('click', () => {
      activePickerMonth++;
      if (activePickerMonth > 11) {
        activePickerMonth = 0;
        activePickerYear++;
      }
      renderM3Calendar();
    });

    // Live Text Input Handling in TEXT_INPUT Mode
    m3TextFieldDate.addEventListener('input', () => {
      const val = (m3TextFieldDate.value || '').trim();
      const parts = val.split('-').map(Number);
      if (parts.length === 3 && parts[0] >= 1900 && parts[0] <= 2100 && parts[1] >= 1 && parts[1] <= 12 && parts[2] >= 1 && parts[2] <= 31) {
        const parsed = new Date(parts[0], parts[1] - 1, parts[2]);
        if (!isNaN(parsed.getTime())) {
          tempSelectedDate = parsed;
          activePickerYear = parsed.getFullYear();
          activePickerMonth = parsed.getMonth();
          updatePickerHeadline();
        }
      }
    });

    btnDateCancel.addEventListener('click', () => {
      m3DateDialog.close();
    });

    btnDateConfirm.addEventListener('click', () => {
      if (datePickerMode === 'TEXT_INPUT') {
        const val = (m3TextFieldDate.value || '').trim();
        const parts = val.split('-').map(Number);
        if (parts.length === 3 && parts[0] >= 1900 && parts[0] <= 2100 && parts[1] >= 1 && parts[1] <= 12 && parts[2] >= 1 && parts[2] <= 31) {
          const parsed = new Date(parts[0], parts[1] - 1, parts[2]);
          if (!isNaN(parsed.getTime())) {
            tempSelectedDate = parsed;
          }
        }
      }

      currentSelectedDate = new Date(tempSelectedDate);
      inputDob.value = formatDate(currentSelectedDate);
      m3DateDialog.close();
      onInputParamChange();
    });

    function onInputParamChange() {
      updateTelemetry(inputName.value || 'Mozi Quantum', inputDob.value || '2000-01-01');
      updateEggState();
      if (engineState !== 'RUNNING') {
        renderSingleFrame();
      }
    }

    inputName.addEventListener('input', onInputParamChange);

    sliderWarp.addEventListener('input', () => {
      valWarp.textContent = parseFloat(sliderWarp.value).toFixed(1);
      if (engineState !== 'RUNNING') renderSingleFrame();
    });

    sliderFlux.addEventListener('input', () => {
      valFlux.textContent = parseFloat(sliderFlux.value).toFixed(1);
      if (engineState !== 'RUNNING') renderSingleFrame();
    });

    sliderSpeed.addEventListener('input', () => {
      valSpeed.textContent = parseFloat(sliderSpeed.value).toFixed(1);
    });

    document.addEventListener('visibilitychange', () => {
      if (document.visibilityState === 'hidden') {
        if (engineState === 'RUNNING') {
          wasRunningBeforeHide = true;
          stopEngine();
        }
      } else if (document.visibilityState === 'visible') {
        if (wasRunningBeforeHide) {
          wasRunningBeforeHide = false;
          startEngine();
        }
      }
    });

  } catch (err) {
    console.error('Failed to initialize Rust WASM Quantum Engine:', err);
    loader.querySelector('.loader-text')!.textContent = t('loader.failed');
  }
}

initApp();
